"""Connector catalog for supported and planned source integrations.

The catalog is intentionally declarative. It gives the app, docs, and extension
runtime a stable contract for every source SudoBrain can ingest or preview
without implying that every vendor API client is already implemented.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Iterable


@dataclass(frozen=True)
class SourceConnectorSpec:
    key: str
    name: str
    category: str
    status: str
    access: str
    auth: str
    document_types: tuple[str, ...]
    default_enabled: bool = False
    env_prefix: str | None = None
    notes: str = ""


SOURCE_CONNECTORS: tuple[SourceConnectorSpec, ...] = (
    SourceConnectorSpec(
        key="github",
        name="GitHub",
        category="engineering",
        status="partial",
        access="read_only",
        auth="personal_access_token_or_github_app",
        document_types=("issues", "pull_requests", "reviews", "discussions", "releases", "commits", "ci_failures"),
        env_prefix="SUDOBRAIN_GITHUB",
        notes="Engineering context, ownership, review decisions, and CI failure memory.",
    ),
    SourceConnectorSpec(
        key="notion",
        name="Notion",
        category="knowledge_base",
        status="partial",
        access="read_only",
        auth="oauth_or_integration_token",
        document_types=("pages", "databases", "meeting_notes", "project_plans", "decision_logs"),
        env_prefix="SUDOBRAIN_NOTION",
    ),
    SourceConnectorSpec(
        key="google_drive",
        name="Google Drive / Docs / Sheets / Slides",
        category="documents",
        status="partial",
        access="read_only",
        auth="oauth",
        document_types=("docs", "sheets", "slides", "pdfs", "folders"),
        env_prefix="SUDOBRAIN_GOOGLE_DRIVE",
    ),
    SourceConnectorSpec(
        key="confluence",
        name="Confluence",
        category="knowledge_base",
        status="partial",
        access="read_only",
        auth="api_token_or_oauth",
        document_types=("pages", "spaces", "runbooks", "architecture_docs"),
        env_prefix="SUDOBRAIN_CONFLUENCE",
    ),
    SourceConnectorSpec(
        key="jira",
        name="Jira",
        category="projects",
        status="partial",
        access="read_only",
        auth="api_token_or_oauth",
        document_types=("issues", "epics", "sprints", "comments", "blockers"),
        env_prefix="SUDOBRAIN_JIRA",
    ),
    SourceConnectorSpec(
        key="asana",
        name="Asana",
        category="projects",
        status="planned",
        access="read_only",
        auth="oauth_or_personal_access_token",
        document_types=("tasks", "projects", "comments", "assignments"),
        env_prefix="SUDOBRAIN_ASANA",
    ),
    SourceConnectorSpec(
        key="trello",
        name="Trello",
        category="projects",
        status="planned",
        access="read_only",
        auth="api_key_token",
        document_types=("boards", "lists", "cards", "comments"),
        env_prefix="SUDOBRAIN_TRELLO",
    ),
    SourceConnectorSpec(
        key="clickup",
        name="ClickUp",
        category="projects",
        status="planned",
        access="read_only",
        auth="api_token_or_oauth",
        document_types=("tasks", "lists", "spaces", "comments"),
        env_prefix="SUDOBRAIN_CLICKUP",
    ),
    SourceConnectorSpec(
        key="monday",
        name="Monday.com",
        category="projects",
        status="planned",
        access="read_only",
        auth="api_token",
        document_types=("boards", "items", "updates", "owners"),
        env_prefix="SUDOBRAIN_MONDAY",
    ),
    SourceConnectorSpec(
        key="microsoft_teams",
        name="Microsoft Teams",
        category="communication",
        status="planned",
        access="read_only",
        auth="microsoft_graph_oauth",
        document_types=("messages", "meetings", "files", "call_transcripts"),
        env_prefix="SUDOBRAIN_TEAMS",
    ),
    SourceConnectorSpec(
        key="zoom",
        name="Zoom",
        category="meetings",
        status="planned",
        access="read_only",
        auth="oauth_or_server_to_server_oauth",
        document_types=("recordings", "transcripts", "summaries", "participants"),
        env_prefix="SUDOBRAIN_ZOOM",
    ),
    SourceConnectorSpec(
        key="google_meet",
        name="Google Meet",
        category="meetings",
        status="planned",
        access="read_only",
        auth="google_workspace_oauth",
        document_types=("calendar_events", "recordings", "transcripts", "summaries"),
        env_prefix="SUDOBRAIN_GOOGLE_MEET",
    ),
    SourceConnectorSpec(
        key="calendar",
        name="Calendar",
        category="meetings",
        status="partial",
        access="read_only",
        auth="oauth_or_local_export",
        document_types=("events", "attendees", "recurrence", "prep_context"),
        env_prefix="SUDOBRAIN_CALENDAR",
    ),
    SourceConnectorSpec(
        key="outlook",
        name="Outlook / Microsoft 365 Mail",
        category="email",
        status="planned",
        access="read_only",
        auth="microsoft_graph_oauth",
        document_types=("messages", "threads", "attachments"),
        env_prefix="SUDOBRAIN_OUTLOOK",
    ),
    SourceConnectorSpec(
        key="imap",
        name="IMAP Mail",
        category="email",
        status="planned",
        access="read_only",
        auth="imap_credentials_or_app_password",
        document_types=("messages", "threads", "attachments"),
        env_prefix="SUDOBRAIN_IMAP",
    ),
    SourceConnectorSpec(
        key="hubspot",
        name="HubSpot",
        category="crm",
        status="planned",
        access="read_only",
        auth="private_app_token_or_oauth",
        document_types=("contacts", "companies", "deals", "notes", "activities"),
        env_prefix="SUDOBRAIN_HUBSPOT",
    ),
    SourceConnectorSpec(
        key="salesforce",
        name="Salesforce",
        category="crm",
        status="planned",
        access="read_only",
        auth="oauth",
        document_types=("accounts", "contacts", "opportunities", "tasks", "notes"),
        env_prefix="SUDOBRAIN_SALESFORCE",
    ),
    SourceConnectorSpec(
        key="pipedrive",
        name="Pipedrive",
        category="crm",
        status="planned",
        access="read_only",
        auth="api_token_or_oauth",
        document_types=("persons", "organizations", "deals", "activities", "notes"),
        env_prefix="SUDOBRAIN_PIPEDRIVE",
    ),
    SourceConnectorSpec(
        key="intercom",
        name="Intercom",
        category="support",
        status="planned",
        access="read_only",
        auth="access_token",
        document_types=("conversations", "tickets", "contacts", "articles"),
        env_prefix="SUDOBRAIN_INTERCOM",
    ),
    SourceConnectorSpec(
        key="zendesk",
        name="Zendesk",
        category="support",
        status="planned",
        access="read_only",
        auth="api_token_or_oauth",
        document_types=("tickets", "comments", "users", "organizations", "articles"),
        env_prefix="SUDOBRAIN_ZENDESK",
    ),
    SourceConnectorSpec(
        key="freshdesk",
        name="Freshdesk",
        category="support",
        status="planned",
        access="read_only",
        auth="api_key",
        document_types=("tickets", "conversations", "contacts", "companies"),
        env_prefix="SUDOBRAIN_FRESHDESK",
    ),
    SourceConnectorSpec(
        key="help_scout",
        name="Help Scout",
        category="support",
        status="planned",
        access="read_only",
        auth="oauth",
        document_types=("conversations", "customers", "mailboxes", "articles"),
        env_prefix="SUDOBRAIN_HELP_SCOUT",
    ),
    SourceConnectorSpec(
        key="pagerduty",
        name="PagerDuty",
        category="incidents",
        status="planned",
        access="read_only",
        auth="api_token_or_oauth",
        document_types=("incidents", "alerts", "services", "on_call"),
        env_prefix="SUDOBRAIN_PAGERDUTY",
    ),
    SourceConnectorSpec(
        key="opsgenie",
        name="Opsgenie",
        category="incidents",
        status="planned",
        access="read_only",
        auth="api_key",
        document_types=("alerts", "incidents", "teams", "schedules"),
        env_prefix="SUDOBRAIN_OPSGENIE",
    ),
    SourceConnectorSpec(
        key="incident_io",
        name="incident.io",
        category="incidents",
        status="planned",
        access="read_only",
        auth="api_key_or_oauth",
        document_types=("incidents", "updates", "postmortems", "roles"),
        env_prefix="SUDOBRAIN_INCIDENT_IO",
    ),
    SourceConnectorSpec(
        key="rootly",
        name="Rootly",
        category="incidents",
        status="planned",
        access="read_only",
        auth="api_token",
        document_types=("incidents", "timeline_events", "postmortems", "services"),
        env_prefix="SUDOBRAIN_ROOTLY",
    ),
    SourceConnectorSpec(
        key="datadog",
        name="Datadog",
        category="observability",
        status="planned",
        access="read_only",
        auth="api_key_app_key",
        document_types=("monitors", "events", "incidents", "dashboards", "logs"),
        env_prefix="SUDOBRAIN_DATADOG",
    ),
    SourceConnectorSpec(
        key="sentry",
        name="Sentry",
        category="observability",
        status="planned",
        access="read_only",
        auth="auth_token",
        document_types=("issues", "events", "releases", "projects"),
        env_prefix="SUDOBRAIN_SENTRY",
    ),
    SourceConnectorSpec(
        key="grafana",
        name="Grafana",
        category="observability",
        status="planned",
        access="read_only",
        auth="service_account_token",
        document_types=("dashboards", "alerts", "annotations", "datasources"),
        env_prefix="SUDOBRAIN_GRAFANA",
    ),
    SourceConnectorSpec(
        key="posthog",
        name="PostHog",
        category="observability",
        status="planned",
        access="read_only",
        auth="personal_api_key",
        document_types=("insights", "dashboards", "experiments", "events"),
        env_prefix="SUDOBRAIN_POSTHOG",
    ),
    SourceConnectorSpec(
        key="amplitude",
        name="Amplitude",
        category="observability",
        status="planned",
        access="read_only",
        auth="api_key_secret_key",
        document_types=("charts", "dashboards", "cohorts", "events"),
        env_prefix="SUDOBRAIN_AMPLITUDE",
    ),
    SourceConnectorSpec(
        key="figma",
        name="Figma",
        category="design",
        status="planned",
        access="read_only",
        auth="oauth_or_personal_access_token",
        document_types=("files", "comments", "projects", "design_review_threads"),
        env_prefix="SUDOBRAIN_FIGMA",
    ),
    SourceConnectorSpec(
        key="raindrop",
        name="Raindrop",
        category="read_later",
        status="planned",
        access="read_only",
        auth="oauth_or_test_token",
        document_types=("bookmarks", "collections", "tags", "annotations"),
        env_prefix="SUDOBRAIN_RAINDROP",
    ),
    SourceConnectorSpec(
        key="pocket",
        name="Pocket",
        category="read_later",
        status="planned",
        access="read_only",
        auth="oauth",
        document_types=("bookmarks", "articles", "tags"),
        env_prefix="SUDOBRAIN_POCKET",
    ),
    SourceConnectorSpec(
        key="browser_history",
        name="Browser History",
        category="read_later",
        status="planned",
        access="local_read_only",
        auth="local_file_permission",
        document_types=("history", "visits", "page_titles"),
        env_prefix="SUDOBRAIN_BROWSER_HISTORY",
    ),
    SourceConnectorSpec(
        key="bookmarks",
        name="Bookmarks",
        category="read_later",
        status="partial",
        access="local_read_only",
        auth="local_capture_or_browser_export",
        document_types=("bookmarks", "webpage_summaries", "tags"),
        env_prefix="SUDOBRAIN_BOOKMARKS",
    ),
    SourceConnectorSpec(
        key="local_files",
        name="Local Files / Folders",
        category="documents",
        status="partial",
        access="local_read_only",
        auth="filesystem_permission",
        document_types=("pdfs", "markdown", "docs", "notes", "exported_chats"),
        env_prefix="SUDOBRAIN_LOCAL_FILES",
    ),
    SourceConnectorSpec(
        key="terminal_activity",
        name="Terminal / Dev Activity",
        category="engineering",
        status="planned",
        access="local_read_only",
        auth="filesystem_permission",
        document_types=("shell_history", "build_failures", "local_logs", "test_runs"),
        env_prefix="SUDOBRAIN_TERMINAL_ACTIVITY",
    ),
    SourceConnectorSpec(
        key="voice_notes",
        name="Voice Notes",
        category="capture",
        status="partial",
        access="local_read_only",
        auth="microphone_or_file_permission",
        document_types=("voice_notes", "transcripts", "reminders"),
        env_prefix="SUDOBRAIN_VOICE_NOTES",
    ),
    SourceConnectorSpec(
        key="mobile_capture",
        name="Mobile Capture",
        category="capture",
        status="partial",
        access="local_capture",
        auth="local_api_token",
        document_types=("quick_thoughts", "decisions", "reminders", "links"),
        env_prefix="SUDOBRAIN_MOBILE_CAPTURE",
    ),
)


def list_source_connectors(category: str | None = None, status: str | None = None) -> list[dict]:
    specs: Iterable[SourceConnectorSpec] = SOURCE_CONNECTORS
    if category:
        specs = (spec for spec in specs if spec.category == category)
    if status:
        specs = (spec for spec in specs if spec.status == status)
    return [asdict(spec) for spec in specs]


def connector_keys() -> set[str]:
    return {spec.key for spec in SOURCE_CONNECTORS}


def connector_categories() -> list[str]:
    return sorted({spec.category for spec in SOURCE_CONNECTORS})
